export enum SkillCategory {
  LANGUAGE = 'LANGUAGE',
  FRAMEWORK = 'FRAMEWORK',
  DATABASE = 'DATABASE',
  DEVOPS = 'DEVOPS',
  CLOUD = 'CLOUD',
  TECHNICAL = 'TECHNICAL',
  TOOL= 'TOOL',
  OTHER = 'OTHER',
}
