export enum ProctoringEventType {
  FACE_NOT_DETECTED = 'FACE_NOT_DETECTED',
  MULTIPLE_FACES_DETECTED = 'MULTIPLE_FACES_DETECTED',
  LOOKING_AWAY = 'LOOKING_AWAY',
  CAMERA_OFF = 'CAMERA_OFF',
  MICROPHONE_MUTED = 'MICROPHONE_MUTED',
  TAB_SWITCHED = 'TAB_SWITCHED',
  FULLSCREEN_EXITED = 'FULLSCREEN_EXITED',
  SUSPICIOUS_INACTIVITY = 'SUSPICIOUS_INACTIVITY',
  NETWORK_DISCONNECTED = 'NETWORK_DISCONNECTED',
  UNKNOWN = 'UNKNOWN',
}
