export enum QuestionType {
  RESUME = 'RESUME',
  SKILL = 'SKILL',
  EXPERIENCE = 'EXPERIENCE',
  PROJECT = 'PROJECT',
  BEHAVIORAL = 'BEHAVIORAL',
  TECHNICAL = 'TECHNICAL',
  FOLLOW_UP = 'FOLLOW_UP',
}
