export enum ActivityEntityType {
  USER = 'USER',
  ROLE = 'ROLE',
  DEPARTMENT = 'DEPARTMENT',
  SKILL = 'SKILL',
  JOB_OPENING = 'JOB_OPENING',
  CANDIDATE = 'CANDIDATE',
  APPLICATION = 'APPLICATION',
  INTERVIEW = 'INTERVIEW',
  DECISION = 'DECISION',
  OFFER = 'OFFER',
  NOTE = 'NOTE',
}
