export enum ActivityActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  STAGE_CHANGE = 'STAGE_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SEND = 'SEND',
  ACCEPT = 'ACCEPT',
  DECLINE = 'DECLINE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}
